"""empty message

Revision ID: 92ef94936108
Revises: 
Create Date: 2021-02-07 22:19:20.055343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ef94936108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('termo_busca', sa.String(), nullable=True),
    sa.Column('tipo_busca', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    # ### end Alembic commands ###
